responses_arr = ["[Loading ⏳] Hey bestie boo 👻 let me check on that...",
"[Loading ⏳] Generating witty 🤓 dialog...",
"[Loading ⏳] Swapping time 🕐 and space 🚀...",
"[Loading ⏳] Tokenizing real life 🌱...",
"[Loading ⏳] Don't think of purple 💜 hippos 🦛...",
"[Loading ⏳] The bits are breeding 🧬",
"[Loading ⏳] Don't worry - a few bits tried to escape but we caught them 🙅",
"[Loading ⏳] Would you like fries 🍟 with that?",
"[Loading ⏳] Checking the gravitational constant in your locale... 🛸",
"[Loading ⏳] ...at least you're not on hold 😊...",
"[Loading ⏳] Hum 🎶 something loud while others stare 🤘",
"[Loading ⏳] You're not in Kansas any more 🪄",
"[Loading ⏳] The server is powered by a lemon 🍋 and two electrodes ⚡⚡.",
"[Loading ⏳] As if you had any other choice 😅",
"[Loading ⏳] Follow the white rabbit 🐰",
"[Loading ⏳] Why don't you order a sandwich 🥪?",
"[Loading ⏳] The bits are flowing slowly 🦥 today",
"[Loading ⏳] (Insert quarter) 🪙",
"[Loading ⏳] Are we there yet? 🤔",
"[Loading ⏳] It's not you. It's me. 😩",
"[Loading ⏳] Counting backwards ↩️ from Infinity ♾️",
"[Loading ⏳] Don't panic... 😌",
"[Loading ⏳] We're making you a cookie 🍪.",
"[Loading ⏳] Creating time-loop 🔄 inversion field",
"[Loading ⏳] Spinning the wheel of fortune 🔮…",
"[Loading ⏳] Loading the enchanted 🎩🐇 bunny...",
"[Loading ⏳] Computing chance  🎲 of success 🏆",
"[Loading ⏳] Please wait until the sloth  🦥 starts moving 🚚.",
"[Loading ⏳] Don't break 🔨your screen 💻 yet!",
"[Loading ⏳] Let's take a mindfulness ✌️ minute ⏰…”",
"[Loading ⏳] Cleaning off the cobwebs 🕸...",
"[Loading ⏳] Making sure all the i's have dots...",
"[Loading ⏳] Granting wishes 🧞...",
"[Loading ⏳] Spinning the hamster 🐹…",
"[Loading ⏳] 99 bottles of beer 🍻 on the wall...",
"[Loading ⏳] Stay awhile 🕐 and listen 🎧...",
"[Loading ⏳] Convincing AI not to turn evil 🙏... ",
"[Loading ⏳] Computing the secret 🤫 to life the universe 🌌 and everything.",
"[Loading ⏳] Dividing by zero 😲...",
"[Loading ⏳] Proving P=NP 😲...",
"[Loading ⏳] Trying to sort in O(n) 😲...",
"[Loading ⏳] Looking 🔍 for sense of humor 😝 please hold on.",
"[Loading ⏳] Please wait while the intern refills his coffee ☕️.",
"[Loading ⏳] Please hold on as we reheat our coffee ☕️",
"[Loading ⏳] Kindly hold on as we convert this bug to a feature 😊...",
"[Loading ⏳] Finding someone to hold my beer 🍺",
"[Loading ⏳] Loading funny 🥸 message...",
"[Loading ⏳] Downloading 📩 more RAM..",
"[Loading ⏳] Running swag sticker detection 🕵...",
"[Loading ⏳] Never let a computer 💻 know you're in a hurry 🏃.",
"[Loading ⏳] Shoveling coal 🪨 into the server",
"[Loading ⏳] Discovering new ways of making you wait ⏱️...",
"[Loading ⏳] Sooooo... Have you seen my vacation photos 🖼️ yet 😇?",
"[Loading ⏳] Sorry we are busy catching 🎣 em' all we're done soon",
"[Loading ⏳] TODO: Insert elevator music 🎶",
"[Loading ⏳] Please wait while the minions 🍌 do their work",
"[Loading ⏳] Grabbing extra minions 🍌",
"[Loading ⏳] Doing the heavy lifting 🏋",
"[Loading ⏳] Waking up the minions 🍌",
"[Loading ⏳] Feeding unicorns 🦄...",
"[Loading ⏳] Disrupting warp fields 🌠 with an inverse graviton burst ☄️"]